### ISSUE TITLE
White lines across screen

### ISSUE THREAD

**Issue by SpyderGiant** [Gaboze-Pocaio/Round-2#10]
I just finished building my gaboze, but I’m having an issue with the screen having white lines across just the top half. Any idea what the problem might be or if I’ve just got a bad screen?
![40F347A9-4955-4EFB-9BD5-2164BA845736](https://user-images.githubusercontent.com/55173452/71610423-c8cf7b80-2b45-11ea-9b26-cddd15671a2c.jpeg)
![90726F43-5FBE-4849-8150-47DD370324E0](https://user-images.githubusercontent.com/55173452/71610424-c8cf7b80-2b45-11ea-84b2-8b5456751883.jpeg)
![D682A3D2-8A86-4E4F-A91D-0DFA9C5D1771](https://user-images.githubusercontent.com/55173452/71610425-c9681200-2b45-11ea-9a08-ef69fb2fa9c6.jpeg)

**Comment by 32teeth** [comment]
Hmm, I would definitely check the soldering of the LCD ribbon

This to me looks like “noise”

**Comment by SpyderGiant** [comment]
Just realized I didn’t post the right pic of the ribbon I soldered. 
![C7A8FCCA-68D3-4CC1-8B60-7D889A00B5D7](https://user-images.githubusercontent.com/55173452/71632473-99f7ea80-2bc3-11ea-8480-b7232cbc7dd7.jpeg)

**Comment by SpyderGiant** [comment]
Solved. Got a new screen from Ali seller and rebuilt for a 3rd time. Working now
![7841B85A-A28E-49E9-A302-4CFC19C97959](https://user-images.githubusercontent.com/55173452/72676115-844b4780-3a42-11ea-9363-9f053482b49b.jpeg)
