### ISSUE TITLE
Incorrect Case Modding Documentation for "Outside Bottom Half Contrast (Brightness)"

### ISSUE THREAD

**Issue by biergaizi** [Gaboze-Pocaio/Round-2#11]
The case modding documentation for "[Outside Bottom Half Contrast (Brightness)](https://github.com/Gaboze-Pocaio/Round-2/wiki/Outside-Bottom-Half---Contrast-%28Brightness%29)" is incorrect, currently a repetition of "[Inside Bottom Half Supports](https://github.com/Gaboze-Pocaio/Round-2/wiki/Inside-Bottom-Half---Supports)", seems to be a copy-and-paste mistake. The brightness wheel and the SD Card doesn't fit and there's no information about how to proceed, please update with the correct documentation, thanks.

**Comment by 32teeth** [comment]
You can use this fo the time being
https://github.com/Gaboze-Pocaio/Round-1/wiki/Shell-Preperation
