### ISSUE TITLE
AC-coupling capacitor C2 should be 220 nF, not 220 pF

### ISSUE THREAD

**Issue by biergaizi** [Gaboze-Pocaio/Round-2#12]
What is the design consideration behind LM4875's input AC coupling capacitor C2? According to the datasheet, the AC coupling capacitor C2 and the input impedance R of LM4875 forms a highpass RC filter. At minimum volume, R = 110kΩ, which means the 3 dB point of the filter is 1 / (2 x π x 110 kΩ x 220 pF) = 6.576 kHz, in other words, the low frequency components, especially bass, is completely blocked by the capacitor. As the volume increases, the 3 dB point moves higher and higher, and cut off more and more frequencies at the lower side. 

Personally, I found the audio quality of the headphone output jack is greatly improved after replacing C2 with a 0.1 uF capacitor.

What is the specific reason to use a 220 pF coupling capacitor here? Is it meant to avoid damaging the GPIO port of the Raspberry Pi when the capacitor discharges?

**Comment by 32teeth** [comment]
> Recommended From TI Datasheet
http://www.ti.com/lit/ds/symlink/lm4875.pdf

**Comment by biergaizi** [comment]
It's not what TI recommended. TI recommends a 0.22 uF capacitor, which is 220 **nF** (or 220e-9), not 220 pF (220e-12). For reference, use `man units` on Linux.

    DESCRIPTION
       Decimal prefixes
           The SI system of units uses prefixes that indicate powers of ten.  
           A kilometer is 1000 meter, and a megawatt is 1000000 watt.
           Below the standard prefixes.

              Prefix   Name    Value
              y        yocto   10^-24 = 0.000000000000000000000001
              z        zepto   10^-21 = 0.000000000000000000001
              a        atto    10^-18 = 0.000000000000000001
              f        femto   10^-15 = 0.000000000000001
              p        pico    10^-12 = 0.000000000001
              n        nano    10^-9  = 0.000000001
              µ        micro   10^-6  = 0.000001
              m        milli   10^-3  = 0.001

I think that the issue should be reopened until a patch is committed to the schematics and BOM. Currently, C2 is 1000x smaller than the value recommended by TI.

**Comment by biergaizi** [comment]
I opened Pull Request #13 with a fix to this problem.
