### ISSUE TITLE
Spot D1

### ISSUE THREAD

**Issue by Vygr10565** [Gaboze-Pocaio/Round-2#5]
Hey 32teeth,

First of all thanks for this awesome project! I was wondering which transistor should be on the D1 spot, circled in blue underneath the Raspberry Pi. And what is it used for?

![board005](https://user-images.githubusercontent.com/47053247/57545880-e3a57380-735b-11e9-82aa-f15619cad655.jpg)

**Comment by 32teeth** [comment]
Designator D1 is a Diode

|  Designator    |   Description   |   MPN   |   Purchase Link   |
| ---- | ---- | ---- | ---- |
|  D1    |   DIODE SCHOTTKY 20V 1A SOD123FL   |   SM5817PL-TP   |   [DigiKey](https://www.digikey.ca/product-detail/en/micro-commercial-co/SM5817PL-TP/SM5817PL-TPMSCT-ND/1793410)   |


[More Here](https://github.com/32teeth/GabozePocaio-Round2/blob/master/bom/GabozePocaioRound2.csv)

**Comment by Vygr10565** [comment]
Will the Raspberry Pi startup without the diode?
