### ISSUE TITLE
What is the Correct Way to Install the 40-Pin Header and the Screen?

### ISSUE THREAD

**Issue by biergaizi** [Gaboze-Pocaio/Round-2#6]
Hello.

I finally started to assemble the board. I was able to install all the components and the system booted successfully. But I found I've soldered the pin header directly, and the pins would penetrate to the other side of the board, together with the solder joints, the screen is impossible to fit on the board, so it's not possible to install the board inside the enclosure. I've read through all the resources about GabozePocaio, but it seems none of them mentioned how to solder the 40-Pin header for the Raspberry Pi mount.

I tried to use a wire-cutter but I found the exposed pins were too short to cut, I also tried to grind the pins out using a Dremel, but I found it's very easy to damage the solder mask in this process. Currently my result of the experiment is three dead boards.

My questions are:

1. What is the correct way to install the header and the screen? Is the pin header in the project BOM a non-standard low-profile version, or is there a special method used here to install it? I've reviewed the spec of TLW-120-06-T-D and I didn't find anything special, so I just used a generic pin header in my toolbox, is it possible that I've missed something?

2. How is the screen installed on the board? How is the proper clearance possible to achieve despite the solder joints between the board and the screen? None of the picture shows what's behind the screen. 

Thanks again for creating this cool project.

**Comment by 32teeth** [comment]
Maybe some pictures will help
![001](https://user-images.githubusercontent.com/75797/59203299-4b71f880-8b6c-11e9-9385-2504d27d6056.jpg)
You can 'PUSH' the pins by placing the header on the board, and from the other side, push each one with flathead screw driver
![002](https://user-images.githubusercontent.com/75797/59203304-4d3bbc00-8b6c-11e9-943b-5bcb9841f89b.jpg)
![003](https://user-images.githubusercontent.com/75797/59203310-5036ac80-8b6c-11e9-8771-8909e6bfe08e.jpg)
![004](https://user-images.githubusercontent.com/75797/59203313-5167d980-8b6c-11e9-93b7-ca414ed90581.jpg)
![005](https://user-images.githubusercontent.com/75797/59203319-53ca3380-8b6c-11e9-89ab-5de2f71ce1da.jpg)
![008](https://user-images.githubusercontent.com/75797/59203323-5593f700-8b6c-11e9-8e69-e8c1722006eb.jpg)
![009](https://user-images.githubusercontent.com/75797/59203326-57f65100-8b6c-11e9-9670-3530c435e1c3.jpg)

**Comment by biergaizi** [comment]
Awesome, thanks!
